### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by zdrjson** [DeveloperPans/PSCarouselView#1]
产品需求：能控制滚动自动的速率，还能用CollectionView吗？后台换掉图片url 客户端要实时刷新，所以必须提供一个检测与刷新方法。

**Comment by MrPans** [comment]
Hi,
如果希望根据url实时更新，只需要将新的url 赋值给PSCarouselView即可。内部已经自动处理刷新了。

//网络请求结束，收到服务器回传的新url数组
    psCarouselView.imageURLs = yourNewImageURLs;

控件目前暂未提供控制滚动数率的接口。下午将会更新，提供控制滚动速度的接口。

**Comment by MrPans** [comment]
目前已提供改变刷新速率的属性：

```
@property (nonatomic) NSTimeInterval movingTimeInterval;/**< 滚动速率 默认为3.0 即3秒翻页一次*/
```

详见PSCarouselView.h文件

**Comment by zdrjson** [comment]
我说的滚动速率是，页面自动滚动的速度，不是间隔多少秒滚动一次！
