### ISSUE TITLE
 不能横竖屏

### ISSUE THREAD

**Issue by laughingg** [DeveloperPans/PSCarouselView#10]
横竖屏切换的时候就有惊天大 bug

**Comment by MrPans** [comment]
`1.3.2` 版本已经修复了这个问题。在 iOS 8及以上系统中，`PSCarouselView` 会根据屏幕的方向自动调整。

 iOS 7 及以下的系统中，请在 ViewController 中监听 `UIDevice` 的通知，并在适当的时候，调用 `-reloadData` 即可。
