### ISSUE TITLE
自写pageController问题和一些建议

### ISSUE THREAD

**Issue by Airende** [DeveloperPans/PSCarouselView#11]
经朋友的推荐很高兴使用你的PSCarouselView，很不错。
但使用过程中发现一点小问题：
在自写pageController，遵循代理，如你demo所写
- (void)carousel:(PSCarouselView *)carousel didMoveToPage:(NSUInteger)page
  {
  self.pageControl.currentPage = page;
  }
  在快速往左滑动后pageControl的店在最后一个停留2次，并不再回到第一个点（demo上可以重现）。

还有一点优化建议：
在图片只有一张的情况下能不能自动使轮播图不自动滚动，并手动也不能滑动。

**Comment by MrPans** [comment]
感谢你的建议，晚点会修复。

**Comment by MrPans** [comment]
Hi, 

BUG已经修复了，相关 enhancement 也已经完成。 更新到 1.4.0 版本即可。： ）

**Comment by Airende** [comment]
修复速度非常快： ），赞！ enhancement部分else 部分匆忙遗漏了吧，导致多张也不能滑动。

**Comment by MrPans** [comment]
是的，昨天晚上也发现了这个 BUG ，会造成轮播无法从禁用滚动状态回到正常状态。
更新到 1.4.1 可解决。

**Comment by Airende** [comment]
OK的
