### ISSUE TITLE
连续快速向一个方向划动广告栏，广告后面会出现黑屏，这是什么原因？

### ISSUE THREAD

**Issue by superzcj** [DeveloperPans/PSCarouselView#5]
demo也能重现

**Comment by MrPans** [comment]
是因为仅在`scrollViewDidEndDecelerating`时判断是否应该回到第一张/回到最后一张。
快速滑动的过程中，不调用`scrollViewDidEndDecelerating`,导致滑动到第一张/最后一张时没有进行循环操作。
最新的版本已经修复了这个问题，在`scrollViewDidScroll`中做一次判断操作即可。
具体请看源码。
感谢BUG的提出 ：)

**Comment by superzcj** [comment]
好快的速度！这个库用着放心
